### ISSUE TITLE
Error when running the LIT-Spacedock

### ISSUE THREAD

**Issue by ZeroDesigner** [litfsindt/LIT-SpaceDock#1]
I am trying to run the software.
And I install the CCDC in my local workstation. Is there any path which I need to change?  

![image](https://github.com/litfsindt/LIT-SpaceDock/assets/32703906/3482a847-ec3a-44fe-9ec4-d5901983ea34)

**Comment by litfsindt** [comment]
Hi,

It seems that it reaches to load building block poses
Are you using a 3.9 version of python ?

François

**Comment by ZeroDesigner** [comment]
> Hi,
> 
> It seems that it reaches to load building block poses Are you using a 3.9 version of python ?
> 
> François

Thanks for your reply.

I make a python3.9 environment.
But it seems still not working.
There is no new file in the output dir.
<img width="877" alt="截屏2024-06-24 20 22 46" src="https://github.com/litfsindt/LIT-SpaceDock/assets/32703906/dd90fdee-b82d-4614-9a33-81c34bca43d4">

**Comment by litfsindt** [comment]
The output is defined by the -o tag, in this case "-o DRD3", it writes outputs file in . (where you launch the command line), with the string "DRD3" as prefix output name.

If you would like to write outputs somewhere else "-o MyOutputFolder/PREFIX"

Here, the "output/" folder present in the github repository contains example of outputs. Normally if you select building block pose in "docked_BBs_DRD3/" (as you did previously), you should obtain the same "DRD3_1.mol2 and DRD3_1.tsv" file, that are in "output/"

Best
François

**Comment by ZeroDesigner** [comment]
> The output is defined by the -o tag, in this case "-o DRD3", it writes outputs file in . (where you launch the command line), with the string "DRD3" as prefix output name.
> 
> If you would like to write outputs somewhere else "-o MyOutputFolder/PREFIX"
> 
> Here, the "output/" folder present in the github repository contains example of outputs. Normally if you select building block pose in "docked_BBs_DRD3/" (as you did previously), you should obtain the same "DRD3_1.mol2 and DRD3_1.tsv" file, that are in "output/"
> 
> Best François

Thanks for your reply.
It works. Amazing.
And I check the generated conformations. It seems that some kind angle is not right. Maybe you can optimize the final conformation with Rdkit or other software ?

<img width="1440" alt="截屏2024-06-24 21 05 41" src="https://github.com/litfsindt/LIT-SpaceDock/assets/32703906/820168cf-804a-4d2b-849d-e6ad4a964c12">

**Comment by litfsindt** [comment]
Yes you're right, generated molecules has to be minimized under the binding site constrain, because there is some bond distance and angles tolerance when it connects two building block pose. In our previous work we use Openeye SZYBKI (MMFF94) for conformation refinement with a threshold of RMSD < 1Å pre-post energy minimization (https://doi.org/10.1021/acscentsci.3c01521). But any tools can be use to refine generated molecules !

**Comment by ZeroDesigner** [comment]
> Yes you're right, generated molecules has to be minimized under the binding site constrain, because there is some bond distance and angles tolerance when it connects two building block pose. In our previous work we use Openeye SZYBKI (MMFF94) for conformation refinement with a threshold of RMSD < 1Å pre-post energy minimization (https://doi.org/10.1021/acscentsci.3c01521). But any tools can be use to refine generated molecules !

Thanks for your reply! It's a good job. : )
Yours Jiaqi.
